### ISSUE TITLE
reductor sum bug

### ISSUE THREAD

**Issue by rzil** [ddemidov/vexcl#177] opened 2015-07-06 09:25 UTC
The following test program produces strange results. Compile with the flag SUM_ON_HOST set to 1 and the result is correct %100 of the time. Compile with SUM_ON_HOST set to 0 and the result is correct about %20 of the time. The problem is traceable to the use of the Reductor class to sum the values in a vector as opposed to summing the values on the host. I take it this is a bug in the Reductor class? Either that or I am not using it correctly.

	// On Mac OS X compile with:
	// clang++ test.cpp -std=gnu++11 -framework OpenCL -lboost_system

	#include <iostream>
	#include <stdexcept>
	#include <vexcl/vexcl.hpp>

	#define SUM_ON_HOST 0

	int main() {
	    vex::Context ctx( vex::Filter::GPU /*&& vex::Filter::DoublePrecision*/ );

	    if (!ctx) throw std::runtime_error("No devices available.");

	    // Print out list of selected devices:
	    std::cout << ctx << std::endl;
	
		const size_t n = 1024;
	
		std::vector<float> h(n);       // Host vector.
		vex::vector<float> d(ctx, n);  // Device vector.
		vex::vector<float> e(ctx, n);  // Device vector.
    
	    vex::Reductor<float, vex::SUM> sum(ctx);
    
	    const long total = 1000;
	    long count = 0;
	    for (size_t i = 0; i < total; i++) {
	        for (size_t i = 0; i < n; i++)
	            h.at(i) = i;
	        vex::copy(h, d);    // Copy data from host to device.
	        e = pow(sin(d),2);	// Compute sin squared of all elements in vector.
        
	        // sum on host
	#if SUM_ON_HOST
	        vex::copy(e, h);
	        float result = std::accumulate(h.begin(),h.end(),0.f);
	#else
	        // use reductor
	        float result = sum(e);	// compute the sum
	#endif
        
	        // check result
	        if ((int)result == 512) {
	            count++;
	        }
	    }
    
		std::cout << (float(count))/total << std::endl;
	
		return 0;
	}

**Comment by ddemidov** [comment] 2015-07-06 09:47
I can not reproduce this on either of my devices (Tesla K40, AMD W9100, Intel CPU) with a slightly modified version of your code: https://gist.github.com/ddemidov/8d21a0883e1fdeffc17d

Did you check if the results are completely wrong, or just slightly off? One reason I can think of is that the result of reduction in floating point arithmetics depends on the summation order, and this effect is more pronounced in single precision. If this is indeed the case, you could try to use Kahan summation:
```cpp
    vex::Reductor<float, vex::SUM_Kahan> sum(ctx);
```
and see if this helps. Another thing to try is to make a similar test with integer vectors, where reduction should be precise. The algorithms used for floating point and for integer vectors are the same, so if there is indeed a bug, you should see it here as well.

**Comment by rzil** [comment] 2015-07-06 10:48
When I changed the Reductor to SUM_Kahan the results improved. It went from around %20 correct to %94.

However, your modified version crashes on my system (Mac OS 10.10.4 MacBook Pro). I will copy paste the output below.


	1. Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (Apple)
	2. HD Graphics 4000 (Apple)

	#if defined(cl_khr_fp64)
	#  pragma OPENCL EXTENSION cl_khr_fp64: enable
	#elif defined(cl_amd_fp64)
	#  pragma OPENCL EXTENSION cl_amd_fp64: enable
	#endif

	kernel void vexcl_vector_kernel
	(
	  ulong n,
	  global float * prm_1,
	  ulong prm_2,
	  int prm_3
	)
	{
	  ulong chunk_size  = (n + get_global_size(0) - 1) / get_global_size(0);
	  ulong chunk_start = get_global_id(0) * chunk_size;
	  ulong chunk_end   = chunk_start + chunk_size;
	  if (n < chunk_end) chunk_end = n;
	  for(ulong idx = chunk_start; idx < chunk_end; ++idx)
	  {
	    prm_1[idx] = pow( sin( (prm_2 + idx) ), prm_3 );
	  }
	}
	<program source>:21:23: error: call to '__fast_relax_sin' is ambiguous
	    prm_1[idx] = pow( sin( (prm_2 + idx) ), prm_3 );
	                      ^~~~~~~~~~~~~~~~~~~~
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4718:22: note: expanded from macro 'sin'
	    #define sin(__x) __fast_relax_sin(__x)
	                     ^~~~~~~~~~~~~~~~
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4662:36: note: expanded from macro 'pow'
	    #define pow(__x, __y) __cl_pow(__x, __y)
	                                   ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:402:27: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline float __OVERLOAD__ _name(float x) { return _default_name(x); } \
	                          ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:403:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline float2 __OVERLOAD__ _name(float2 x) { return _default_name(x); } \
	                           ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:404:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline float3 __OVERLOAD__ _name(float3 x) { return _default_name(x); } \
	                           ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:405:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline float4 __OVERLOAD__ _name(float4 x) { return _default_name(x); } \
	                           ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:406:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline float8 __OVERLOAD__ _name(float8 x) { return _default_name(x); } \
	                           ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:407:29: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline float16 __OVERLOAD__ _name(float16 x){ return _default_name(x); } \
	                            ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:408:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline double __OVERLOAD__ _name(double x) { return _default_name(x); } \
	                           ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:409:29: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline double2 __OVERLOAD__ _name(double2 x) { return _default_name(x); } \
	                            ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:410:29: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline double3 __OVERLOAD__ _name(double3 x) { return _default_name(x); } \
	                            ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:411:29: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline double4 __OVERLOAD__ _name(double4 x) { return _default_name(x); } \
	                            ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:412:29: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline double8 __OVERLOAD__ _name(double8 x) { return _default_name(x); } \
	                            ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4716:30: note: candidate function
	    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_sin, native_sin, __cl_sin);
	                             ^
	/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:413:30: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
	inline double16 __OVERLOAD__ _name(double16 x) { return _default_name(x); }
	                             ^

	libc++abi.dylib: terminating with uncaught exception of type cl::Error: clBuildProgram
	Abort trap: 6

Ruben

**Comment by ddemidov** [comment] 2015-07-06 11:11
Re the compilation error: either
```cpp
e = pow(sin(convert_float(vex::element_index())), 2);
```
or
```cpp
e = pow(sin(1.0f * vex::element_index()), 2);
```
should work.

Can you please post the output of the following program on your system? 
```cpp
#include <iostream>
#include <stdexcept>
#include <vexcl/vexcl.hpp>

int main() {
    vex::Context ctx( vex::Filter::Env );
    std::cout << ctx << std::endl;

    const size_t n = 1024;

    std::vector<float> h(n);       // Host vector.
    vex::vector<float> e(ctx, n);  // Device vector.

    vex::Reductor<float, vex::SUM> sum(ctx);

    const long total = 1000;
    double m1 = 0, m2 = 0, lo, hi;
    for (size_t i = 0; i < total; i++) {
        e = pow(sin(convert_float(vex::element_index())), 2);
        double s = sum(e);
        m1 += s;
        m2 += s * s;
        lo = (i == 0) ? s : std::min(lo, s);
        hi = (i == 0) ? s : std::max(lo, s);
    }

    m1 /= total;
    m2 /= total;

    std::cout << "min  = " << lo << std::endl;
    std::cout << "max  = " << hi << std::endl;
    std::cout << "mean = " << m1 << std::endl;
    std::cout << "var  = " << m2 - m1*m1 << std::endl;

    return 0;
}
```
For me its
```
$ OCL_DEVICE=Intel ./hello 
1. Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (AMD Accelerated Parallel Processing)

min  = 512.038
max  = 512.038
mean = 512.038
var  = 0

$ OCL_DEVICE=K40 ./hello 
1. Tesla K40c (NVIDIA CUDA)

min  = 512.038
max  = 512.038
mean = 512.038
var  = -3.25963e-09

$ OCL_DEVICE=Hawaii ./hello 
1. Hawaii (AMD Accelerated Parallel Processing)

min  = 512.038
max  = 512.038
mean = 512.038
var  = -7.27596e-09
```

**Comment by rzil** [comment] 2015-07-06 21:49
That fixed the compilation error. Here is the output of the program you asked me to test.

1. Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (Apple)
2. HD Graphics 4000 (Apple)

min  = 463.917
max  = 512.038
mean = 510.547
var  = 39.209

Ruben

**Comment by ddemidov** [comment] 2015-07-07 08:28
That does look like a bug is present somewhere. Can you please run the following test? It tests integer and floating point reduction on both of your devices (although I suspect the GPU is the one at fault).
```cpp
#include <iostream>
#include <vexcl/vexcl.hpp>

template <typename T>
void test_sum(const vex::Context &ctx) {
    const size_t n = 1024;
    const size_t m = 1000;

    vex::vector<T> x(ctx, n);
    vex::Reductor<T, vex::SUM> sum(ctx);

    T lo, hi;

    for (size_t i = 0; i < m; i++) {
        x = static_cast<T>(1);
        T s = sum(x);

        lo = (i == 0) ? s : std::min(lo, s);
        hi = (i == 0) ? s : std::max(hi, s);
    }

    std::cout << "  "
        << vex::type_name<T>() << " "
        << "(" << lo << " - " << hi << ")"
        << std::endl;
}

int main() {
    for(auto &ctx : {
            vex::Context(vex::Filter::GPU && vex::Filter::Count(1)),
            vex::Context(vex::Filter::CPU && vex::Filter::Count(1))
            })
    {
        std::cout << ctx.queue(0) << std::endl;
        std::cout << "  "
            << "CL_DEVICE_MAX_WORK_ITEM_SIZES[0] = "
            << ctx.device(0).getInfo<CL_DEVICE_MAX_WORK_ITEM_SIZES>()[0]
            << std::endl;

        test_sum<float>(ctx);
        test_sum< int >(ctx);
    }
}
```

**Comment by rzil** [comment] 2015-07-07 08:31
Here is the output

HD Graphics 4000 (Apple)
  CL_DEVICE_MAX_WORK_ITEM_SIZES[0] = 512
  float (896 - 1216)
  int (832 - 1024)
Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (Apple)
  CL_DEVICE_MAX_WORK_ITEM_SIZES[0] = 1024
  float (1024 - 1024)
  int (1024 - 1024)

Ruben

**Comment by ddemidov** [comment] 2015-07-07 09:04
Thank you. I think I know where the problem is. Can you see if d7de741 solves the issue for you? Same test as above should suffice.

**Comment by rzil** [comment] 2015-07-07 11:00
That seems to have worked. See below results.

HD Graphics 4000 (Apple)
  CL_DEVICE_MAX_WORK_ITEM_SIZES[0] = 512
  float (1024 - 1024)
  int (1024 - 1024)
Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (Apple)
  CL_DEVICE_MAX_WORK_ITEM_SIZES[0] = 1024
  float (1024 - 1024)
  int (1024 - 1024)

Ruben

**Comment by ddemidov** [comment] 2015-07-07 11:02
Merged to master. Thanks for both reporting and testing!

**Closed by ddemidov** 2015-07-07 11:02 UTC

**Comment by rzil** [comment] 2015-07-08 00:35
No problem at all.
Ruben
