### ISSUE TITLE
Build failure with gcc 5.1-5.2

### ISSUE THREAD

**Issue by torquil** [ddemidov/vexcl#178] opened 2015-09-03 09:13 UTC
When building VexCL, I get this error:

.
.
.
[ 38%] Building CXX object tests/CMakeFiles/random.dir/random.cpp.o
cd /home/tmac/src/vexcl/build/tests && /usr/bin/c++   -DBOOST_TEST_DYN_LINK -DHAVE_FFTW -DVEXCL_BACKEND_OPENCL -DVEXCL_CACHE_KERNELS -DVEXCL_CHECK_SIZES=2 -fopenmp -std=c++0x -Wall -Wclobbered -Wempty-body -Wmissing-field-initializers -Wsign-compare -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wno-comment -Wno-type-limits -Wno-strict-aliasing -Wno-missing-braces -I/home/tmac/src/vexcl -I/home/tmac/usr/include    -o CMakeFiles/random.dir/random.cpp.o -c /home/tmac/src/vexcl/tests/random.cpp
In file included from /home/tmac/src/vexcl/vexcl/backend/opencl.hpp:49:0,
                 from /home/tmac/src/vexcl/vexcl/backend.hpp:74,
                 from /home/tmac/src/vexcl/vexcl/vector.hpp:48,
                 from /home/tmac/src/vexcl/tests/random.cpp:3:
/home/tmac/src/vexcl/vexcl/backend/opencl/device_vector.hpp: In instantiation of ‘class vex::backend::opencl::device_vector<unsigned int>’:
/home/tmac/src/vexcl/vexcl/vector.hpp:618:9:   required from ‘class vex::vector<unsigned int>’
/home/tmac/src/vexcl/tests/random.cpp:21:29:   required from here
/home/tmac/src/vexcl/vexcl/backend/opencl/device_vector.hpp:110:55: internal compiler error: in strip_typedefs, at cp/tree.c:1369
         typedef std::unique_ptr<T[], buffer_unmapper> mapped_array;
                                                       ^
0x6d870e strip_typedefs(tree_node*)
	../../src/gcc/cp/tree.c:1369
0x61b0cc canonicalize_type_argument
	../../src/gcc/cp/pt.c:6574
0x62e662 coerce_template_parms
	../../src/gcc/cp/pt.c:7245
0x62f5d8 lookup_template_class_1
	../../src/gcc/cp/pt.c:7854
0x62f5d8 lookup_template_class(tree_node*, tree_node*, tree_node*, tree_node*, int, int)
	../../src/gcc/cp/pt.c:8170
0x631aec tsubst_aggr_type
	../../src/gcc/cp/pt.c:10575
0x626ac1 tsubst(tree_node*, tree_node*, int, tree_node*)
	../../src/gcc/cp/pt.c:12034
0x634032 tsubst_decl
	../../src/gcc/cp/pt.c:11458
0x626e84 tsubst(tree_node*, tree_node*, int, tree_node*)
	../../src/gcc/cp/pt.c:11955
0x63e3c9 instantiate_class_template_1
	../../src/gcc/cp/pt.c:9520
0x63e3c9 instantiate_class_template(tree_node*)
	../../src/gcc/cp/pt.c:9792
0x69949d complete_type(tree_node*)
	../../src/gcc/cp/typeck.c:146
0x62708f tsubst(tree_node*, tree_node*, int, tree_node*)
	../../src/gcc/cp/pt.c:12566
0x630d2b tsubst_function_type
	../../src/gcc/cp/pt.c:11749
0x626b74 tsubst(tree_node*, tree_node*, int, tree_node*)
	../../src/gcc/cp/pt.c:12482
0x6332ae tsubst_decl
	../../src/gcc/cp/pt.c:10960
0x626e84 tsubst(tree_node*, tree_node*, int, tree_node*)
	../../src/gcc/cp/pt.c:11955
0x63e781 instantiate_class_template_1
	../../src/gcc/cp/pt.c:9470
0x63e781 instantiate_class_template(tree_node*)
	../../src/gcc/cp/pt.c:9792
0x69949d complete_type(tree_node*)
	../../src/gcc/cp/typeck.c:146
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
tests/CMakeFiles/random.dir/build.make:57: recipe for target 'tests/CMakeFiles/random.dir/random.cpp.o' failed
make[2]: *** [tests/CMakeFiles/random.dir/random.cpp.o] Error 1
make[2]: Leaving directory '/home/tmac/src/vexcl/build'
CMakeFiles/Makefile2:554: recipe for target 'tests/CMakeFiles/random.dir/all' failed
make[1]: *** [tests/CMakeFiles/random.dir/all] Error 2
make[1]: Leaving directory '/home/tmac/src/vexcl/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

My OS is Debian Sid, with

$ gcc --version
gcc (Debian 5.2.1-15) 5.2.1 20150808

I've got OpenCL 1.1 header files and Boost 1.58 installed.

**Comment by ddemidov** [comment] 2015-09-03 09:16
That's a known issue with gcc 5.1 and 5.2: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66121. Should be fixed for gcc 5.3.

**Comment by torquil** [comment] 2015-09-03 11:16
On 03/09/15 11:16, Denis Demidov wrote:
>
> That's a known issue with gcc 5.1 and 5.2:
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66121. Should be fixed
> for gcc 5.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ddemidov/vexcl/issues/178#issuecomment-137387846>.
>

Thanks! I tried again on a different machine with a newer GCC weekly
snapshot (5.2.1 20150901) and the build now proceeds further, but I end
up with a different error:

In file included from
/mn/anatu/cma-u3/tmac/usr/include/boost/test/unit_test.hpp:19:0,
                 from
/mn/anatu/cma-u3/tmac/external/build/src/vexcl/tests/cast.cpp:2:
/mn/anatu/cma-u3/tmac/external/build/src/vexcl/tests/context_setup.hpp:
At global scope:
/mn/anatu/cma-u3/tmac/usr/include/boost/test/unit_test_suite.hpp:50:1:
error: expected initializer before ‘namespace’
 namespace suite_name {                                                  \
 ^
/mn/anatu/cma-u3/tmac/usr/include/boost/test/unit_test_suite.hpp:58:5:
note: in expansion of macro ‘BOOST_AUTO_TEST_SUITE_WITH_DECOR’
     BOOST_AUTO_TEST_SUITE_WITH_DECOR(                                   \
     ^
/mn/anatu/cma-u3/tmac/usr/include/boost/test/unit_test_suite.hpp:90:5:
note: in expansion of macro ‘BOOST_AUTO_TEST_SUITE_NO_DECOR’
     BOOST_AUTO_TEST_SUITE_NO_DECOR( suite_name )                        \
     ^
/mn/anatu/cma-u3/tmac/usr/include/boost/test/detail/pp_variadic.hpp:27:51:
note: in expansion of macro ‘BOOST_FIXTURE_TEST_SUITE_NO_DECOR’
 #  define BOOST_TEST_INVOKE_VARIADIC( tool, ... ) tool (__VA_ARGS__)
                                                   ^
/mn/anatu/cma-u3/tmac/usr/include/boost/test/detail/pp_variadic.hpp:35:5: note:
in expansion of macro ‘BOOST_TEST_INVOKE_VARIADIC’
     BOOST_TEST_INVOKE_VARIADIC(                                     \
     ^
/mn/anatu/cma-u3/tmac/usr/include/boost/preprocessor/control/iif.hpp:25:39:
note: in expansion of macro ‘BOOST_PP_IIF_1’
 #    define BOOST_PP_IIF_I(bit, t, f) BOOST_PP_IIF_ ## bit(t, f)
                                       ^
/mn/anatu/cma-u3/tmac/usr/include/boost/preprocessor/control/iif.hpp:18:37:
note: in expansion of macro ‘BOOST_PP_IIF_I’
 #    define BOOST_PP_IIF(bit, t, f) BOOST_PP_IIF_I(bit, t, f)
                                     ^
/mn/anatu/cma-u3/tmac/usr/include/boost/test/detail/pp_variadic.hpp:36:9: note:
in expansion of macro ‘BOOST_PP_IIF’
         BOOST_PP_IIF(                                               \
         ^
/mn/anatu/cma-u3/tmac/usr/include/boost/test/unit_test_suite.hpp:97:5:
note: in expansion of macro ‘BOOST_TEST_INVOKE_IF_N_ARGS’
     BOOST_TEST_INVOKE_IF_N_ARGS( 2,                                     \
     ^
/mn/anatu/cma-u3/tmac/external/build/src/vexcl/tests/context_setup.hpp:71:1:
note: in expansion of macro ‘BOOST_FIXTURE_TEST_SUITE’
 BOOST_FIXTURE_TEST_SUITE(cr, ContextReference)
 ^
In file included from
/mn/anatu/cma-u3/tmac/usr/include/boost/system/system_error.hpp:14:0,
                 from
/mn/anatu/cma-u3/tmac/usr/include/boost/thread/exceptions.hpp:22,
                 from
/mn/anatu/cma-u3/tmac/usr/include/boost/thread/pthread/thread_data.hpp:10,
                 from
/mn/anatu/cma-u3/tmac/usr/include/boost/thread/thread_only.hpp:17,
                 from
/mn/anatu/cma-u3/tmac/usr/include/boost/thread/thread.hpp:12,
                 from /mn/anatu/cma-u3/tmac/usr/include/boost/thread.hpp:13,
                 from
/mn/anatu/cma-u3/tmac/external/build/src/vexcl/vexcl/vector.hpp:46,
                 from
/mn/anatu/cma-u3/tmac/external/build/src/vexcl/tests/cast.cpp:3:
/mn/anatu/cma-u3/tmac/usr/include/boost/system/error_code.hpp:221:36:
warning: ‘boost::system::posix_category’ defined but not used
[-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
/mn/anatu/cma-u3/tmac/usr/include/boost/system/error_code.hpp:222:36:
warning: ‘boost::system::errno_ecat’ defined but not used
[-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
/mn/anatu/cma-u3/tmac/usr/include/boost/system/error_code.hpp:223:36:
warning: ‘boost::system::native_ecat’ defined but not used
[-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
make[2]: *** [tests/CMakeFiles/cast.dir/cast.cpp.o] Error 1
make[2]: Leaving directory `/run/media/tmac/External/build/src/vexcl/build'
make[1]: *** [tests/CMakeFiles/cast.dir/all] Error 2
make[1]: Leaving directory `/run/media/tmac/External/build/src/vexcl/build'
make: *** [all] Error 2

**Comment by ddemidov** [comment] 2015-09-03 11:24
This looks like a Boost.Test issue. What version of boost do you use?

**Comment by ddemidov** [comment] 2015-09-03 11:55
I think I can reproduce the issue with boost 1.59 and clang.

**Comment by ddemidov** [comment] 2015-09-03 12:02
Should be fixed in 38ad35e.

**Comment by ddemidov** [comment] 2015-12-14 07:01
I can confirm that they fixed the issue in gcc v5.3.

**Closed by ddemidov** 2015-12-14 07:01 UTC
Labels: Known issue
